### ISSUE TITLE
what is the schedule in "Groovy scheduled tasks"

### ISSUE THREAD

**Issue by scm20008** [mailru/jira-scripts#1]
@nteplov 

Hi Nikita,

when I create the "Groovy scheduled tasks", I have a problem with this.

Please tell me what is the meaning of "schedule", it is as follows:
![2018-05-03_152221](https://user-images.githubusercontent.com/639305/39564256-0ba59018-4ee6-11e8-9c3d-8ae3857a3941.jpg)

and Could you tell me what the syntax is?

Thanks!

**Comment by lexek** [comment]
Hi. Sorry for delayed response.

This repository is only for script examples. For any groovy plugin questions or issues, you should create issue in plugin repository mailru/jira-plugins-groovy.

It's minutes or quartz cron expression. We'll add description for this field in next release.
