### ISSUE TITLE
Enhancement: sendEmail function with attachments

### ISSUE THREAD

**Issue by holle** [mailru/jira-scripts#4]
Hi,

as an enhancement for:
mygroovy-kit/global objects/_.groovy
This code works (I have tested it) for sending out EMails with one or more attachments (should be even robust against attachments == null):

    /** Отправить email
     * @param emailAddr : "test@test.test"
     * @param copy - ящики которые нужно добавить в копию, указываются через запятую.
     * @param subject - шаблон для заголовка сообщений.
     * @param body - тело сообщения.
     * @param from - адрес, который будет указан как отправитель этого сообщения. По умолчанию адрес JIRA.
     * @param replyTo - адрес, на который будет отправлен ответ на письмо.
     * @param emailFormat - "text/html" or "text/plain" or ...
     * @param attachments - list of attachments
     * */
    void sendEmail(String emailAddr, String copy, String subject, String body, String from, String replyTo, String emailFormat, List<Attachment> attachments) {
        Email email = new Email(emailAddr, copy, '')
        email.setSubject(subject)
        Multipart multipart = new MimeMultipart("mixed")
        
        if (from) {
            email.setFrom(from)
        }
        if (replyTo) {
            email.setReplyTo(replyTo)
        }
        // add body
        MimeBodyPart bodyPart = new MimeBodyPart()
        bodyPart.setContent(body, "${emailFormat}; charset=utf-8")
        multipart.addBodyPart(bodyPart)
        
        attachments?.each {
            File attachment = AttachmentUtils.getAttachmentFile(it)
        
            MimeBodyPart attachmentPart = new MimeBodyPart()
            attachmentPart.attachFile(attachment, it.getMimetype(), null)
            attachmentPart.setFileName(it.getFilename())
            multipart.addBodyPart(attachmentPart)
        }
        email.setMultipart(multipart)
        email.setMimeType("multipart/mixed")
        SingleMailQueueItem smqi = new SingleMailQueueItem(email)
        ComponentAccessor.getMailQueue().addItem(smqi)
    }

**Comment by holle** [comment]
See here for the full File, including all required import statements
[_.groovy.zip](https://github.com/mailru/jira-scripts/files/3708157/_.groovy.zip)

**Comment by chuikoaleksandr** [comment]
Hello! Thank. 
Added your code. You can also send pull requests. :)
