### ISSUE TITLE
Enhancement for send a custom email with attachments

### ISSUE THREAD

**Issue by holle** [mailru/jira-scripts#5]
Hi,

as an enhancement for
mygroovy-kit/registry/function/send a custom email.groovy

This change works (and has been tested both with and without attachments):

Lines 144 and following:

    if (stringEmailsTo) {
        if(attachments) {
            _.sendEmail(stringEmailsTo, stringCopyTo, subject, body, from, replyTo, emailFormat, attachments)
        } else {
            _.sendEmail(stringEmailsTo, stringCopyTo, subject, body, from, replyTo, emailFormat)
        }
    }

**Comment by chuikoaleksandr** [comment]
Hello! Thank. 
Added your code. You can also send pull requests. :)
